#!/usr/bin/env node
import { realpathSync } from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import readline from 'node:readline/promises';
import { fileURLToPath } from 'node:url';

const GENERATED_BY = 'Generated by scripts/setup-ci.mjs.';
const GITIGNORE_START = '# >>> setup-ci generated ignores >>>';
const GITIGNORE_END = '# <<< setup-ci generated ignores <<<';

export const TOOL_ORDER = [
  'js-ts',
  'python',
  'swift',
  'go',
  'rust',
  'github-actions',
  'bash',
  'markdown',
  'docker',
];

export const TOOL_DEFINITIONS = {
  'js-ts': {
    label: 'HTML/JavaScript/TypeScript',
    description: 'pnpm, ESLint, Prettier, Vite, and Vitest',
  },
  python: {
    label: 'Python',
    description: 'uv, Ruff, Pyright, and pytest',
  },
  swift: {
    label: 'Swift',
    description: 'swift-format, SwiftLint, and swift test',
  },
  go: {
    label: 'Go',
    description: 'gofmt, go vet, go test, and go test benchmarks',
  },
  rust: {
    label: 'Rust',
    description: 'cargo fmt, cargo clippy, cargo test, and cargo bench',
  },
  'github-actions': {
    label: 'GitHub Actions',
    description: 'actionlint',
  },
  bash: {
    label: 'Bash scripts',
    description: 'shfmt, shellcheck, and bash -n',
  },
  markdown: {
    label: 'Markdown',
    description: 'Prettier and markdownlint-cli2',
  },
  docker: {
    label: 'Docker',
    description: 'hadolint and docker buildx build --check',
  },
};

const COMMON_IGNORES = ['.cache/', 'coverage/', '.coverage', '*.log'];

const TOOL_IGNORES = {
  'js-ts': ['node_modules/', 'dist/', 'build/', 'out/', 'coverage/'],
  python: ['.venv/', '.ruff_cache/', '.pytest_cache/', '.pyright/', '__pycache__/', '*.py[cod]'],
  swift: ['.build/', '.swiftpm/', 'DerivedData/'],
  go: ['bin/', 'coverage.out'],
  rust: ['target/'],
  bash: [],
  'github-actions': [],
  markdown: ['node_modules/'],
  docker: [],
};

const PACKAGE_MANAGER = 'pnpm@11.5.2';

class UsageError extends Error {
  constructor(message) {
    super(message);
    this.name = 'UsageError';
  }
}

export function parseArgs(argv) {
  const options = {
    tools: [],
    all: false,
    benchmark: false,
    dryRun: false,
    force: false,
    help: false,
    list: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--help' || arg === '-h') {
      options.help = true;
    } else if (arg === '--list') {
      options.list = true;
    } else if (arg === '--all') {
      options.all = true;
    } else if (arg === '--benchmark') {
      options.benchmark = true;
    } else if (arg === '--dry-run') {
      options.dryRun = true;
    } else if (arg === '--force') {
      options.force = true;
    } else if (arg === '--tool' || arg === '-t') {
      const value = argv[index + 1];
      if (!value || value.startsWith('-')) {
        throw new UsageError(`${arg} requires a tool name.`);
      }
      options.tools.push(...parseToolList(value));
      index += 1;
    } else if (arg.startsWith('--tool=')) {
      options.tools.push(...parseToolList(arg.slice('--tool='.length)));
    } else {
      throw new UsageError(`Unknown argument: ${arg}`);
    }
  }

  if (options.all && options.tools.length > 0) {
    throw new UsageError('Use either --all or --tool, not both.');
  }

  options.tools = uniqueTools(options.tools);
  validateTools(options.tools);
  return options;
}

export function parseToolList(value) {
  return value
    .split(',')
    .map((part) => part.trim())
    .filter(Boolean);
}

export function usage() {
  return `Usage:
  node scripts/setup-ci.mjs
  node scripts/setup-ci.mjs --tool js-ts --tool python --tool docker
  node scripts/setup-ci.mjs --all --benchmark --dry-run

Options:
  -t, --tool <name>   Select a supported tool module. Repeat or comma-separate.
      --all           Select every supported module.
      --benchmark     Generate scripts/benchmark.sh for selected benchmarkable tools.
      --dry-run       Print planned writes without changing files.
      --force         Overwrite conflicting generated targets.
      --list          List supported modules.
  -h, --help          Show this help.
`;
}

export function listTools() {
  return TOOL_ORDER.map((tool, index) => {
    const definition = TOOL_DEFINITIONS[tool];
    return `${index + 1}. ${tool}: ${definition.label} (${definition.description})`;
  }).join('\n');
}

function validateTools(tools) {
  const unsupported = tools.filter((tool) => !TOOL_DEFINITIONS[tool]);
  if (unsupported.length > 0) {
    throw new UsageError(`Unsupported tool module: ${unsupported.join(', ')}`);
  }
}

function uniqueTools(tools) {
  return [...new Set(tools)];
}

function resolveTools(options) {
  if (options.all) {
    return [...TOOL_ORDER];
  }
  return uniqueTools(options.tools);
}

export async function runCli({
  argv = process.argv.slice(2),
  cwd = process.cwd(),
  stdin = process.stdin,
  stdout = process.stdout,
  stderr = process.stderr,
} = {}) {
  try {
    const options = parseArgs(argv);

    if (options.help) {
      stdout.write(usage());
      return 0;
    }

    if (options.list) {
      stdout.write(`${listTools()}\n`);
      return 0;
    }

    let tools = resolveTools(options);
    let benchmark = options.benchmark;

    if (tools.length === 0) {
      if (!stdin.isTTY || !stdout.isTTY) {
        throw new UsageError(
          'No tools selected. Pass --tool, --all, or run interactively in a TTY.',
        );
      }
      const interactive = await promptForSelection({ stdin, stdout });
      tools = interactive.tools;
      benchmark = interactive.benchmark;
    }

    if (tools.length === 0) {
      throw new UsageError('No tools selected.');
    }

    const plan = buildFilePlan({ tools, benchmark });
    const result = await applyFilePlan({
      cwd,
      files: plan.files,
      dryRun: options.dryRun,
      force: options.force,
      stdout,
    });

    stdout.write(
      `${options.dryRun ? 'Planned' : 'Applied'} ${result.changed.length} file change(s); ` +
        `${result.unchanged.length} unchanged.\n`,
    );
    return 0;
  } catch (error) {
    const status = error instanceof UsageError ? 2 : 1;
    stderr.write(`${error.message}\n`);
    if (error instanceof UsageError) {
      stderr.write('\n');
      stderr.write(usage());
    }
    return status;
  }
}

async function promptForSelection({ stdin, stdout }) {
  const rl = readline.createInterface({ input: stdin, output: stdout });
  try {
    stdout.write('Supported tool modules:\n');
    stdout.write(`${listTools()}\n\n`);
    const selected = await rl.question(
      'Select tools by name or number, comma-separated (default: all): ',
    );
    const tools = parseInteractiveSelection(selected);
    const benchmarkAnswer = await rl.question('Generate scripts/benchmark.sh? [y/N]: ');
    const benchmark = /^y(es)?$/i.test(benchmarkAnswer.trim());
    return { tools, benchmark };
  } finally {
    rl.close();
  }
}

export function parseInteractiveSelection(value) {
  const trimmed = value.trim();
  if (!trimmed || trimmed.toLowerCase() === 'all') {
    return [...TOOL_ORDER];
  }

  const tools = trimmed
    .split(/[,\s]+/)
    .map((part) => part.trim())
    .filter(Boolean)
    .map((token) => {
      if (/^\d+$/.test(token)) {
        const index = Number(token) - 1;
        if (index < 0 || index >= TOOL_ORDER.length) {
          throw new UsageError(`Tool number out of range: ${token}`);
        }
        return TOOL_ORDER[index];
      }
      return token;
    });

  validateTools(tools);
  return uniqueTools(tools);
}

export function buildFilePlan({ tools, benchmark = false }) {
  const selected = new Set(tools);
  validateTools([...selected]);

  const files = [
    {
      path: '.github/workflows/ci.yml',
      content: buildCiWorkflow(selected),
    },
    {
      path: '.gitignore',
      kind: 'gitignore-block',
      entries: buildGitignoreEntries(selected),
    },
  ];

  if (selected.size > 0) {
    files.push({
      path: '.editorconfig',
      content: editorConfig(),
    });
  }

  if (selected.has('js-ts') || selected.has('markdown')) {
    files.push({
      path: 'package.json',
      kind: 'json-merge',
      patch: buildPackagePatch(selected),
    });
    files.push({
      path: 'prettier.config.mjs',
      content: prettierConfig(),
    });
    files.push({
      path: '.prettierignore',
      content: prettierIgnore(),
    });
  }

  if (selected.has('js-ts')) {
    files.push(
      {
        path: 'eslint.config.mjs',
        content: eslintConfig(),
      },
      {
        path: 'tsconfig.json',
        content: tsconfig(),
      },
      {
        path: 'vite.config.ts',
        content: viteConfig(),
      },
    );
  }

  if (selected.has('markdown')) {
    files.push({
      path: '.markdownlint-cli2.jsonc',
      content: markdownlintConfig(),
    });
  }

  if (selected.has('python')) {
    files.push({
      path: 'pyproject.toml',
      content: pyprojectToml({ benchmark }),
    });
  }

  if (selected.has('swift')) {
    files.push({
      path: '.swiftlint.yml',
      content: swiftlintConfig(),
    });
  }

  if (selected.has('docker')) {
    files.push({
      path: '.hadolint.yaml',
      content: hadolintConfig(),
    });
  }

  if (benchmark) {
    files.push({
      path: 'scripts/benchmark.sh',
      content: benchmarkScript(selected),
      executable: true,
    });
  }

  return { tools: [...selected], benchmark, files };
}

function buildPackagePatch(selected) {
  const devDependencies = {};
  const scripts = {
    format: 'prettier --write .',
    'format:check': 'prettier --check .',
  };
  const lintScripts = [];

  if (selected.has('js-ts')) {
    Object.assign(devDependencies, {
      '@eslint/js': '^10.0.1',
      '@types/node': '^24.13.1',
      eslint: '^10.4.1',
      globals: '^17.6.0',
      prettier: '^3.8.3',
      typescript: '^6.0.3',
      'typescript-eslint': '^8.60.1',
      vite: '^8.0.16',
      vitest: '^4.1.8',
    });
    scripts['lint:js'] = 'eslint .';
    scripts.test = 'vitest run --passWithNoTests';
    scripts['test:watch'] = 'vitest';
    scripts.bench = 'vitest bench';
    lintScripts.push('pnpm run lint:js');
  }

  if (selected.has('markdown')) {
    Object.assign(devDependencies, {
      'markdownlint-cli2': '^0.22.1',
      prettier: devDependencies.prettier ?? '^3.8.3',
    });
    scripts['lint:markdown'] = 'markdownlint-cli2';
    lintScripts.push('pnpm run lint:markdown');
  }

  if (lintScripts.length > 0) {
    scripts.lint = lintScripts.join(' && ');
  }

  return {
    name: 'replace-me',
    version: '0.1.0',
    private: true,
    type: 'module',
    packageManager: PACKAGE_MANAGER,
    scripts,
    devDependencies,
  };
}

function buildGitignoreEntries(selected) {
  const entries = new Set(COMMON_IGNORES);
  for (const tool of selected) {
    for (const entry of TOOL_IGNORES[tool] ?? []) {
      entries.add(entry);
    }
  }
  return [...entries].sort();
}

export async function applyFilePlan({
  cwd,
  files,
  dryRun = false,
  force = false,
  stdout = process.stdout,
}) {
  const prepared = [];
  const conflicts = [];

  for (const file of files) {
    const absolutePath = path.join(cwd, file.path);
    const existing = await readTextIfExists(absolutePath);
    let content;
    let conflict;

    if (file.kind === 'gitignore-block') {
      content = applyGitignoreBlock(existing ?? '', file.entries);
    } else if (file.kind === 'json-merge') {
      const merged = mergeJsonFile(existing, file.patch, { force });
      content = merged.content;
      conflict = merged.conflict;
    } else {
      content = file.content;
      if (existing !== null && existing !== content && !force) {
        conflict = `${file.path} already exists with different content. Re-run with --force to overwrite.`;
      }
    }

    if (conflict) {
      conflicts.push(conflict);
      continue;
    }

    const changed = existing !== content;
    prepared.push({ ...file, absolutePath, content, changed });
  }

  if (conflicts.length > 0) {
    throw new Error(
      `Refusing to overwrite conflicting files:\n${conflicts.map((item) => `- ${item}`).join('\n')}`,
    );
  }

  const changed = [];
  const unchanged = [];

  for (const file of prepared) {
    if (file.changed) {
      changed.push(file.path);
      if (dryRun) {
        stdout.write(`[dry-run] write ${file.path}\n`);
      } else {
        await fs.mkdir(path.dirname(file.absolutePath), { recursive: true });
        await fs.writeFile(file.absolutePath, file.content, 'utf8');
      }
    } else {
      unchanged.push(file.path);
      if (dryRun) {
        stdout.write(`[dry-run] unchanged ${file.path}\n`);
      }
    }

    if (file.executable && !dryRun) {
      await fs.chmod(file.absolutePath, 0o755);
    }
  }

  return { changed, unchanged };
}

async function readTextIfExists(filePath) {
  try {
    return await fs.readFile(filePath, 'utf8');
  } catch (error) {
    if (error && error.code === 'ENOENT') {
      return null;
    }
    throw error;
  }
}

function applyGitignoreBlock(existing, entries) {
  const block = `${GITIGNORE_START}\n${entries.join('\n')}\n${GITIGNORE_END}\n`;
  const startIndex = existing.indexOf(GITIGNORE_START);
  const endIndex = existing.indexOf(GITIGNORE_END);

  if (startIndex !== -1 && endIndex !== -1 && endIndex > startIndex) {
    const before = existing.slice(0, startIndex);
    const rawAfter = existing.slice(endIndex + GITIGNORE_END.length);
    const after = rawAfter.trim() ? rawAfter.replace(/^\n?/, '\n') : '';
    return `${before}${block}${after}`.replace(/\n{3,}/g, '\n\n');
  }

  if (!existing.trim()) {
    return block;
  }

  const trimmed = existing.endsWith('\n') ? existing : `${existing}\n`;
  return `${trimmed}\n${block}`;
}

function mergeJsonFile(existing, patch, { force }) {
  if (existing === null) {
    return { content: `${JSON.stringify(patch, null, 2)}\n` };
  }

  let parsed;
  try {
    parsed = JSON.parse(existing);
  } catch (error) {
    return { conflict: `package.json is not valid JSON: ${error.message}` };
  }

  const merged = { ...parsed };
  const conflicts = [];

  for (const key of ['name', 'version', 'private', 'packageManager']) {
    if (merged[key] === undefined) {
      merged[key] = patch[key];
    } else if (key === 'packageManager' && merged[key] !== patch[key]) {
      if (force) {
        merged[key] = patch[key];
      } else {
        conflicts.push(
          `package.json packageManager is ${JSON.stringify(merged[key])}, expected ${JSON.stringify(patch[key])}`,
        );
      }
    }
  }

  merged.scripts = mergeObjectField('package.json scripts', merged.scripts, patch.scripts, {
    force,
    conflicts,
  });
  merged.devDependencies = mergeObjectField(
    'package.json devDependencies',
    merged.devDependencies,
    patch.devDependencies,
    { force, conflicts },
  );

  if (conflicts.length > 0) {
    return { conflict: conflicts.join('\n') };
  }

  return { content: `${JSON.stringify(merged, null, 2)}\n` };
}

function mergeObjectField(label, existingValue, patchValue, { force, conflicts }) {
  const merged = { ...(existingValue ?? {}) };
  for (const [key, value] of Object.entries(patchValue)) {
    if (merged[key] === undefined || merged[key] === value || force) {
      merged[key] = value;
    } else {
      conflicts.push(`${label}.${key} already exists with different value.`);
    }
  }
  return merged;
}

function buildCiWorkflow(selected) {
  const jobs = [];
  if (selected.has('js-ts') || selected.has('markdown')) {
    jobs.push(nodeToolingJob(selected));
  }
  if (selected.has('python')) {
    jobs.push(pythonJob());
  }
  if (selected.has('swift')) {
    jobs.push(swiftJob());
  }
  if (selected.has('go')) {
    jobs.push(goJob());
  }
  if (selected.has('rust')) {
    jobs.push(rustJob());
  }
  if (selected.has('github-actions') || selected.has('bash') || selected.has('docker')) {
    jobs.push(repoHygieneJob(selected));
  }

  const toolList = [...selected].join(', ');
  return `# ${GENERATED_BY}
# Selected modules: ${toolList}
name: CI

on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-\${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
${jobs.join('\n\n')}
`;
}

function nodeToolingJob(selected) {
  const steps = [step('Check formatting', 'pnpm run format:check')];
  if (selected.has('js-ts')) {
    steps.push(step('Lint JavaScript and TypeScript', 'pnpm run lint:js'));
  }
  if (selected.has('markdown')) {
    steps.push(step('Lint Markdown', 'pnpm run lint:markdown'));
  }
  if (selected.has('js-ts')) {
    steps.push(step('Run JavaScript and TypeScript tests', 'pnpm test'));
  }

  return `  node-tooling:
    name: Node tooling
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: Set up Node
        if: \${{ hashFiles('pnpm-lock.yaml') == '' }}
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Set up Node with pnpm cache
        if: \${{ hashFiles('pnpm-lock.yaml') != '' }}
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install --no-frozen-lockfile
          fi
${steps.join('\n')}`;
}

function pythonJob() {
  return `  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Install dependencies
        run: uv sync --group dev
      - name: Check Python formatting
        run: uv run ruff format --check .
      - name: Lint Python
        run: uv run ruff check .
      - name: Type-check Python
        run: uv run pyright
      - name: Run Python tests
        run: |
          if [ ! -d tests ]; then
            echo "No tests/ directory found; skipping pytest."
            exit 0
          fi

          set +e
          uv run pytest
          status=$?
          set -e
          if [ "$status" -eq 5 ]; then
            echo "No Python tests found; skipping pytest."
          else
            exit "$status"
          fi`;
}

function swiftJob() {
  return `  swift:
    name: Swift
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install Swift tooling
        run: brew install swiftlint swift-format
      - name: Run Swift checks
        run: |
          if [ ! -f Package.swift ]; then
            echo "No Package.swift found; skipping Swift checks."
            exit 0
          fi

          swift_paths=()
          [ -f Package.swift ] && swift_paths+=(Package.swift)
          [ -d Sources ] && swift_paths+=(Sources)
          [ -d Tests ] && swift_paths+=(Tests)

          swift-format lint --strict --recursive "\${swift_paths[@]}"
          swiftlint lint --strict --no-cache
          swift test`;
}

function goJob() {
  return `  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run Go checks
        run: |
          if [ ! -f go.mod ]; then
            echo "No go.mod found; skipping Go checks."
            exit 0
          fi

          mapfile -t go_files < <(find . -type f -name '*.go' -not -path './vendor/*' -not -path './.git/*')
          if [ "\${#go_files[@]}" -eq 0 ]; then
            echo "No Go files found; skipping Go checks."
            exit 0
          fi

          unformatted="$(gofmt -l "\${go_files[@]}")"
          if [ -n "$unformatted" ]; then
            echo "$unformatted"
            exit 1
          fi

          go vet ./...
          go test ./...`;
}

function rustJob() {
  return `  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Run Rust checks
        run: |
          if [ ! -f Cargo.toml ]; then
            echo "No Cargo.toml found; skipping Rust checks."
            exit 0
          fi

          cargo fmt --check
          cargo clippy --all-targets --all-features -- -D warnings
          cargo test --all-features`;
}

function repoHygieneJob(selected) {
  const needsGoInstall = selected.has('github-actions') || selected.has('bash');
  const steps = ['      - name: Check out repository\n        uses: actions/checkout@v6'];

  if (needsGoInstall) {
    steps.push(`      - name: Set up Go for lint tools
        uses: actions/setup-go@v6
        with:
          go-version: stable`);
  }

  const installLines = [];
  if (selected.has('github-actions')) {
    installLines.push('go install github.com/rhysd/actionlint/cmd/actionlint@latest');
  }
  if (selected.has('bash')) {
    installLines.push('sudo apt-get update');
    installLines.push('sudo apt-get install -y shellcheck');
    installLines.push('go install mvdan.cc/sh/v3/cmd/shfmt@latest');
  }
  if (installLines.length > 0) {
    steps.push(`      - name: Install repository lint tools
        run: |
          ${installLines.join('\n          ')}
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"`);
  }

  if (selected.has('github-actions')) {
    steps.push(step('Lint GitHub Actions workflows', 'actionlint'));
  }
  if (selected.has('bash')) {
    steps.push(`      - name: Check shell scripts
        run: |
          mapfile -t shell_files < <(find . -type f \\( -name '*.sh' -o -name '*.bash' \\) -not -path './.git/*' -not -path './node_modules/*' -not -path './dist/*' -not -path './build/*' -not -path './out/*' -not -path './target/*')
          if [ "\${#shell_files[@]}" -eq 0 ]; then
            echo "No shell scripts found; skipping shell checks."
            exit 0
          fi

          shfmt -d -i 2 -ci -sr "\${shell_files[@]}"
          shellcheck "\${shell_files[@]}"
          for file in "\${shell_files[@]}"; do
            bash -n "$file"
          done`);
  }
  if (selected.has('docker')) {
    steps.push(`      - name: Check Dockerfiles
        run: |
          mapfile -t dockerfiles < <(find . -type f \\( -name 'Dockerfile' -o -name 'Dockerfile.*' \\) -not -path './.git/*' -not -path './node_modules/*' -not -path './dist/*' -not -path './build/*' -not -path './out/*' -not -path './target/*')
          if [ "\${#dockerfiles[@]}" -eq 0 ]; then
            echo "No Dockerfiles found; skipping Docker checks."
            exit 0
          fi

          docker run --rm -v "$PWD:/workspace" -w /workspace hadolint/hadolint:latest "\${dockerfiles[@]}"
          for dockerfile in "\${dockerfiles[@]}"; do
            docker buildx build --check -f "$dockerfile" "$(dirname "$dockerfile")"
          done`);
  }

  return `  repo-hygiene:
    name: Repository hygiene
    runs-on: ubuntu-latest
    steps:
${steps.join('\n')}`;
}

function step(name, run) {
  return `      - name: ${name}
        run: ${run}`;
}

function editorConfig() {
  return `# ${GENERATED_BY}
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.{md,markdown}]
trim_trailing_whitespace = false
`;
}

function prettierConfig() {
  return `// ${GENERATED_BY}
export default {
  printWidth: 100,
  singleQuote: true,
  trailingComma: 'all',
};
`;
}

function prettierIgnore() {
  return `# ${GENERATED_BY}
node_modules/
pnpm-lock.yaml
package-lock.json
yarn.lock
bun.lock
bun.lockb
dist/
build/
out/
target/
coverage/
.venv/
`;
}

function eslintConfig() {
  return `// ${GENERATED_BY}
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: ['dist/**', 'build/**', 'out/**', 'coverage/**', 'node_modules/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{js,cjs,mjs,ts,cts,mts}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.vitest,
      },
    },
  },
);
`;
}

function tsconfig() {
  return `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "skipLibCheck": true,
    "types": ["node", "vitest/globals"],
    "noEmit": true
  },
  "include": ["src", "test", "tests", "*.config.*"]
}
`;
}

function viteConfig() {
  return `// ${GENERATED_BY}
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    passWithNoTests: true,
  },
});
`;
}

function markdownlintConfig() {
  return `{
  "config": {
    "default": true,
    "MD013": false,
  },
  "globs": ["**/*.md", "!node_modules", "!dist", "!build", "!out", "!target"],
}
`;
}

function pyprojectToml({ benchmark }) {
  const benchmarkGroup = benchmark
    ? `
benchmark = [
  "pytest-benchmark>=5,<6",
]
`
    : '';

  return `# ${GENERATED_BY}
[project]
name = "replace-me"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
  "pyright>=1.1,<2",
  "pytest>=9,<10",
  "ruff>=0.14,<1",
]
${benchmarkGroup}
[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "standard"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
`;
}

function swiftlintConfig() {
  return `# ${GENERATED_BY}
included:
  - Sources
  - Tests
  - Package.swift
excluded:
  - .build
  - .swiftpm
disabled_rules:
  - trailing_comma
line_length:
  warning: 120
  error: 160
opt_in_rules:
  - empty_count
  - sorted_imports
`;
}

function hadolintConfig() {
  return `# ${GENERATED_BY}
failure-threshold: warning
ignored: []
`;
}

function benchmarkScript(selected) {
  const sections = [];

  if (selected.has('js-ts')) {
    sections.push(`if [ -f package.json ]; then
  require_command pnpm
  run_step "JavaScript/TypeScript benchmarks" pnpm run bench
else
  echo "Skipping JavaScript/TypeScript benchmarks: package.json not found."
fi`);
  }

  if (selected.has('python')) {
    sections.push(`if [ -f pyproject.toml ]; then
  require_command uv
  run_step "Python benchmarks" uv run --group benchmark pytest --benchmark-only
else
  echo "Skipping Python benchmarks: pyproject.toml not found."
fi`);
  }

  if (selected.has('go')) {
    sections.push(`if [ -f go.mod ]; then
  require_command go
  run_step "Go benchmarks" go test -bench . -benchmem ./...
else
  echo "Skipping Go benchmarks: go.mod not found."
fi`);
  }

  if (selected.has('rust')) {
    sections.push(`if [ -f Cargo.toml ]; then
  require_command cargo
  run_step "Rust benchmarks" cargo bench
else
  echo "Skipping Rust benchmarks: Cargo.toml not found."
fi`);
  }

  return `#!/usr/bin/env bash
# ${GENERATED_BY}
set -euo pipefail

ran=0

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 127
  fi
}

run_step() {
  local label="$1"
  shift
  printf '\\n==> %s\\n' "$label"
  "$@"
  ran=1
}

${sections.join('\n\n')}

if [ "$ran" -eq 0 ]; then
  echo "No benchmark commands were run for the selected modules."
fi
`;
}

function isDirectRun() {
  if (!process.argv[1]) {
    return false;
  }

  try {
    return (
      realpathSync.native(fileURLToPath(import.meta.url)) ===
      realpathSync.native(path.resolve(process.argv[1]))
    );
  } catch (error) {
    if (error?.code === 'ENOENT') {
      return false;
    }
    throw error;
  }
}

if (isDirectRun()) {
  const status = await runCli();
  process.exitCode = status;
}
